"""Stable process exit codes for uWatt CLI commands."""

SUCCESS = 0
TEST_FAILURE = 1
INVALID_CONFIGURATION = 2
HARDWARE_UNAVAILABLE = 3
INVALID_EXPERIMENT = 4
ANALYSIS_FAILURE = 5
INCOMPATIBLE_BASELINE = 6
